services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile  
    container_name: mysql_dbase
    restart: always    
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-soap:
    build:
      context: ./BANPAIS_SOAP_API
      dockerfile: Dockerfile
    container_name: backend_soap
    restart: always
    ports:
      - "8080:8080"


  backend-rest:
    build:
      context: ./banpais-rest-api
      dockerfile: Dockerfile
    container_name: backend_rest
    restart: always
    ports:
      - "8081:8081"


  frontend:
    build:
       context: ./frontend-transactional-challenge
       dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
     - "5176:5176"


volumes:
  mysql_data:
  # frontend_node_modules: