package com.banpais.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-25T23:45:42.304-06:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "BancoPortService",
                  wsdlLocation = "file:/C:/Users/gcalvaradoa/Desktop/BC_BANPAIS/banpais-rest-api/src/main/resources/banco.wsdl",
                  targetNamespace = "http://www.example.com/banco")
public class BancoPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.com/banco", "BancoPortService");
    public final static QName BancoPortSoap11 = new QName("http://www.example.com/banco", "BancoPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/gcalvaradoa/Desktop/BC_BANPAIS/banpais-rest-api/src/main/resources/banco.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BancoPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/gcalvaradoa/Desktop/BC_BANPAIS/banpais-rest-api/src/main/resources/banco.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BancoPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BancoPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BancoPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BancoPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BancoPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BancoPort
     */
    @WebEndpoint(name = "BancoPortSoap11")
    public BancoPort getBancoPortSoap11() {
        return super.getPort(BancoPortSoap11, BancoPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoPort
     */
    @WebEndpoint(name = "BancoPortSoap11")
    public BancoPort getBancoPortSoap11(WebServiceFeature... features) {
        return super.getPort(BancoPortSoap11, BancoPort.class, features);
    }

}
