package com.example.banco;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-25T11:42:21.444-06:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.example.com/banco", name = "BancoPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BancoPort {

    @WebMethod
    @WebResult(name = "actualizarClienteResponse", targetNamespace = "http://www.example.com/banco", partName = "actualizarClienteResponse")
    public ActualizarClienteResponse actualizarCliente(

        @WebParam(partName = "actualizarClienteRequest", name = "actualizarClienteRequest", targetNamespace = "http://www.example.com/banco")
        ActualizarClienteRequest actualizarClienteRequest
    );

    @WebMethod
    @WebResult(name = "registrarCuentaResponse", targetNamespace = "http://www.example.com/banco", partName = "registrarCuentaResponse")
    public RegistrarCuentaResponse registrarCuenta(

        @WebParam(partName = "registrarCuentaRequest", name = "registrarCuentaRequest", targetNamespace = "http://www.example.com/banco")
        RegistrarCuentaRequest registrarCuentaRequest
    );

    @WebMethod
    @WebResult(name = "eliminarCuentaResponse", targetNamespace = "http://www.example.com/banco", partName = "eliminarCuentaResponse")
    public EliminarCuentaResponse eliminarCuenta(

        @WebParam(partName = "eliminarCuentaRequest", name = "eliminarCuentaRequest", targetNamespace = "http://www.example.com/banco")
        EliminarCuentaRequest eliminarCuentaRequest
    );

    @WebMethod
    @WebResult(name = "registrarClienteResponse", targetNamespace = "http://www.example.com/banco", partName = "registrarClienteResponse")
    public RegistrarClienteResponse registrarCliente(

        @WebParam(partName = "registrarClienteRequest", name = "registrarClienteRequest", targetNamespace = "http://www.example.com/banco")
        RegistrarClienteRequest registrarClienteRequest
    );

    @WebMethod
    @WebResult(name = "eliminarClienteResponse", targetNamespace = "http://www.example.com/banco", partName = "eliminarClienteResponse")
    public EliminarClienteResponse eliminarCliente(

        @WebParam(partName = "eliminarClienteRequest", name = "eliminarClienteRequest", targetNamespace = "http://www.example.com/banco")
        EliminarClienteRequest eliminarClienteRequest
    );

    @WebMethod
    @WebResult(name = "registrarMovimientoResponse", targetNamespace = "http://www.example.com/banco", partName = "registrarMovimientoResponse")
    public RegistrarMovimientoResponse registrarMovimiento(

        @WebParam(partName = "registrarMovimientoRequest", name = "registrarMovimientoRequest", targetNamespace = "http://www.example.com/banco")
        RegistrarMovimientoRequest registrarMovimientoRequest
    );

    @WebMethod
    @WebResult(name = "actualizarCuentaResponse", targetNamespace = "http://www.example.com/banco", partName = "actualizarCuentaResponse")
    public ActualizarCuentaResponse actualizarCuenta(

        @WebParam(partName = "actualizarCuentaRequest", name = "actualizarCuentaRequest", targetNamespace = "http://www.example.com/banco")
        ActualizarCuentaRequest actualizarCuentaRequest
    );
}
